server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Angular-Routing: immer index.html ausliefern
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Optional: statische Dateien direkt ausliefern
    location /assets/ {
        try_files $uri $uri/ =404;
    }
}
