name: Build Angular Frontend

on:
  push:
    paths:
      - "Frontend/**" # Action läuft nur, wenn sich im Frontend-Ordner etwas ändert
    branches:
      - main # auf welchem Branch? -> ggf. "master" oder "develop" anpassen

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Repo auschecken
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Node.js installieren
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.12.0"
          cache: "npm"
          cache-dependency-path: Frontend/package-lock.json

      # 3. Dependencies installieren
      - name: Install dependencies
        working-directory: ./Frontend
        run: npm install

      # 4. Angular Build ausführen
      - name: Build Angular project
        working-directory: ./Frontend
        run: npm run build
